"""Scripted demo scenarios for DisOps.

Each scenario is an ordered list of frame templates. The orchestrator walks the
list (looping at the end), emitting one frame every 2-3 seconds. Frames are
written to feel like a real incident unfolding: monitoring → first signal →
escalation → guidance → stabilization.

Only brief, user-safe reasoning is included — never long chain-of-thought.
"""

from __future__ import annotations

from typing import Any

# A scenario frame is a partial PipelineEvent. Missing fields fall back to the
# dataclass defaults in models.PipelineEvent.
Frame = dict[str, Any]

SCENARIOS: dict[str, dict[str, Any]] = {
    "no_hazard": {
        "label": "No hazard detected",
        "icon": "shield",
        "frames": [
            {
                "urgency": "Low",
                "scene_summary": "Indoor hallway, well lit, no obstructions visible.",
                "situation": "No active incident.",
                "voice_guidance": "Monitoring your environment. No immediate danger detected.",
                "reasoning_summary": "Scene is clear with no hazard signatures.",
                "next_check": "Continue monitoring for changes in smoke, motion, or crowding.",
                "risk_level": "Low",
                "safest_next_action": "Proceed normally and stay aware of your surroundings.",
                "uncertainty": "None significant.",
                "detected_hazards": [],
                "detected_objects": ["door", "floor", "ceiling lights"],
                "people_detected": 0,
                "environment_conditions": ["normal visibility", "stable lighting"],
                "motion_changes": "Stable",
                "confidence": 0.94,
            },
            {
                "urgency": "Low",
                "scene_summary": "Corridor remains clear, one person walking calmly.",
                "situation": "No active incident.",
                "voice_guidance": "All clear. Continue as normal.",
                "reasoning_summary": "Routine pedestrian movement, no hazard.",
                "next_check": "Watch for sudden motion or appearance of smoke.",
                "risk_level": "Low",
                "safest_next_action": "Continue on your current path.",
                "uncertainty": "None significant.",
                "detected_hazards": [],
                "detected_objects": ["person", "door", "exit sign"],
                "people_detected": 1,
                "environment_conditions": ["normal visibility"],
                "motion_changes": "Minor",
                "confidence": 0.91,
            },
        ],
    },
    "fire_smoke": {
        "label": "Fire / Smoke",
        "icon": "flame",
        "frames": [
            {
                "urgency": "Low",
                "scene_summary": "Indoor hallway, lighting normal, faint haze near the left wall.",
                "situation": "Possible early smoke signal near the doorway.",
                "voice_guidance": "Monitoring environment. A faint haze is visible, staying alert.",
                "reasoning_summary": "Low-density haze could be dust or early smoke.",
                "next_check": "Confirm whether haze thickens or spreads toward the exit.",
                "risk_level": "Low",
                "safest_next_action": "Stay aware and be ready to move away from the left side.",
                "uncertainty": "Source of haze is not yet confirmed.",
                "detected_hazards": [],
                "detected_objects": ["door", "wall", "haze"],
                "people_detected": 1,
                "environment_conditions": ["slight haze", "normal lighting"],
                "motion_changes": "Minor",
                "confidence": 0.62,
            },
            {
                "urgency": "Medium",
                "scene_summary": "Visible smoke gathering near the left side of the doorway.",
                "situation": "Smoke detected near an exit route.",
                "voice_guidance": "Potential risk detected. Smoke is forming near the doorway, stay aware.",
                "reasoning_summary": "Smoke near an exit can indicate fire risk or poor air quality.",
                "next_check": "Check whether smoke is spreading and whether another exit is visible.",
                "risk_level": "Medium",
                "safest_next_action": "Begin moving away from the smoke and toward a clear exit.",
                "uncertainty": "Source of smoke is not confirmed.",
                "detected_hazards": ["smoke"],
                "detected_objects": ["door", "smoke", "person"],
                "people_detected": 1,
                "environment_conditions": ["reduced visibility", "smoke"],
                "motion_changes": "Increasing",
                "confidence": 0.79,
            },
            {
                "urgency": "High",
                "scene_summary": "Dense smoke spreading across the hallway, visibility dropping fast.",
                "situation": "Possible smoke or fire hazard blocking an exit route.",
                "voice_guidance": "Move away from the smoke now. Stay low and look for the nearest clear exit.",
                "reasoning_summary": "Spreading smoke near an exit strongly suggests fire and unsafe air.",
                "next_check": "Confirm an alternate exit is clear before moving toward it.",
                "risk_level": "High",
                "safest_next_action": "Stay low, cover your mouth, and move to an alternate clear exit.",
                "uncertainty": "Exact fire source not visible in frame.",
                "detected_hazards": ["smoke", "blocked_exit", "low_visibility"],
                "detected_objects": ["door", "smoke", "person"],
                "people_detected": 1,
                "environment_conditions": ["low visibility", "heavy smoke"],
                "motion_changes": "Rapid",
                "confidence": 0.88,
            },
            {
                "urgency": "Critical",
                "scene_summary": "Flames now visible at the base of the doorway, smoke filling the corridor.",
                "situation": "Active fire at the primary exit.",
                "voice_guidance": "Immediate danger. Do not use this exit. Stay low and go to the opposite end of the hallway now.",
                "reasoning_summary": "Visible flame plus heavy smoke confirms active fire at this exit.",
                "next_check": "Locate the secondary exit and confirm it is free of smoke.",
                "risk_level": "Critical",
                "safest_next_action": "Crawl low away from the flames toward the secondary exit immediately.",
                "uncertainty": "Status of the secondary exit is not yet confirmed.",
                "detected_hazards": ["fire", "smoke", "blocked_exit"],
                "detected_objects": ["fire", "smoke", "door", "person"],
                "people_detected": 1,
                "environment_conditions": ["very low visibility", "active flame", "heavy smoke"],
                "motion_changes": "Rapid",
                "confidence": 0.93,
            },
        ],
    },
    "flooding": {
        "label": "Flooding",
        "icon": "wave",
        "frames": [
            {
                "urgency": "Medium",
                "scene_summary": "Water pooling across the lower stairwell, depth rising slowly.",
                "situation": "Rising water detected on the evacuation route.",
                "voice_guidance": "Potential risk detected. Water is rising on the lower route, avoid it.",
                "reasoning_summary": "Standing water on a route can hide hazards and conduct electricity.",
                "next_check": "Find a higher route and check for live electrical sources nearby.",
                "risk_level": "Medium",
                "safest_next_action": "Avoid the water and move to higher ground.",
                "uncertainty": "Water depth and current strength not fully visible.",
                "detected_hazards": ["flood_water"],
                "detected_objects": ["stairs", "water", "railing"],
                "people_detected": 0,
                "environment_conditions": ["standing water", "wet surfaces"],
                "motion_changes": "Increasing",
                "confidence": 0.81,
            },
            {
                "urgency": "High",
                "scene_summary": "Fast-moving water now covers the corridor floor and is rising.",
                "situation": "Rapidly rising flood water blocking the ground route.",
                "voice_guidance": "Danger. Do not walk through the moving water. Move to higher ground immediately.",
                "reasoning_summary": "Moving flood water can sweep a person off balance even at shallow depth.",
                "next_check": "Confirm a stairway or upper floor is reachable and dry.",
                "risk_level": "High",
                "safest_next_action": "Go up. Use the nearest stairs to reach a higher, dry level.",
                "uncertainty": "Whether upper floors remain dry is unconfirmed.",
                "detected_hazards": ["flood_water", "blocked_exit"],
                "detected_objects": ["water", "corridor", "stairs"],
                "people_detected": 1,
                "environment_conditions": ["moving water", "rising level"],
                "motion_changes": "Rapid",
                "confidence": 0.87,
            },
        ],
    },
    "earthquake": {
        "label": "Earthquake debris",
        "icon": "blocks",
        "frames": [
            {
                "urgency": "High",
                "scene_summary": "Ceiling debris and fallen tiles partially block the hallway.",
                "situation": "Structural debris obstructing the path after shaking.",
                "voice_guidance": "Danger. Debris is blocking the path. Watch overhead and move carefully to clear space.",
                "reasoning_summary": "Fallen debris signals possible structural instability overhead.",
                "next_check": "Identify a clear span away from hanging or cracked sections.",
                "risk_level": "High",
                "safest_next_action": "Move away from overhead hazards toward a structurally clear area.",
                "uncertainty": "Stability of the remaining ceiling is unknown.",
                "detected_hazards": ["debris", "blocked_exit", "falling_object"],
                "detected_objects": ["debris", "ceiling tiles", "wall crack"],
                "people_detected": 1,
                "environment_conditions": ["dust", "obstructed path"],
                "motion_changes": "Settling",
                "confidence": 0.84,
            },
            {
                "urgency": "Critical",
                "scene_summary": "A section of ceiling has collapsed; more material is shifting above.",
                "situation": "Active structural collapse risk overhead.",
                "voice_guidance": "Immediate danger. Get under sturdy cover or move clear of the ceiling now and protect your head.",
                "reasoning_summary": "Ongoing movement above indicates imminent further collapse.",
                "next_check": "Confirm a sturdy table, doorway frame, or open exterior is reachable.",
                "risk_level": "Critical",
                "safest_next_action": "Take cover under something sturdy or get outside, protecting your head.",
                "uncertainty": "Extent of structural damage is unknown.",
                "detected_hazards": ["falling_object", "debris", "blocked_exit"],
                "detected_objects": ["collapsed ceiling", "debris", "person"],
                "people_detected": 1,
                "environment_conditions": ["active collapse", "heavy dust"],
                "motion_changes": "Rapid",
                "confidence": 0.9,
            },
        ],
    },
    "blocked_exit": {
        "label": "Blocked exit",
        "icon": "block",
        "frames": [
            {
                "urgency": "Medium",
                "scene_summary": "Stacked boxes and a cart partially obstruct the marked exit.",
                "situation": "Primary exit is partially blocked by obstacles.",
                "voice_guidance": "Potential risk. The main exit is partly blocked, look for an alternate route.",
                "reasoning_summary": "A partially blocked exit slows evacuation and may fully block under crowding.",
                "next_check": "Locate the nearest alternate exit and confirm it is clear.",
                "risk_level": "Medium",
                "safest_next_action": "Identify and head toward an alternate clear exit.",
                "uncertainty": "Whether the blockage can be moved is unclear.",
                "detected_hazards": ["blocked_exit"],
                "detected_objects": ["boxes", "cart", "exit sign", "door"],
                "people_detected": 2,
                "environment_conditions": ["obstructed exit", "normal visibility"],
                "motion_changes": "Minor",
                "confidence": 0.83,
            },
            {
                "urgency": "High",
                "scene_summary": "The exit is now fully blocked and a small crowd is gathering.",
                "situation": "Primary exit fully blocked with people accumulating.",
                "voice_guidance": "Danger. This exit is blocked. Do not crowd here, move to the alternate exit now.",
                "reasoning_summary": "A fully blocked exit with crowding raises crush and entrapment risk.",
                "next_check": "Direct movement steadily toward the confirmed alternate exit.",
                "risk_level": "High",
                "safest_next_action": "Move calmly but quickly to the alternate exit, avoid pushing.",
                "uncertainty": "Capacity of the alternate exit is unconfirmed.",
                "detected_hazards": ["blocked_exit", "crowd"],
                "detected_objects": ["boxes", "crowd", "door", "exit sign"],
                "people_detected": 5,
                "environment_conditions": ["crowding", "obstructed exit"],
                "motion_changes": "Increasing",
                "confidence": 0.86,
            },
        ],
    },
    "person_fallen": {
        "label": "Person fallen",
        "icon": "person",
        "frames": [
            {
                "urgency": "High",
                "scene_summary": "A person is on the floor near the corridor, not moving.",
                "situation": "Possible fall or medical emergency.",
                "voice_guidance": "A person appears to have fallen. If it is safe, check responsiveness and call for help.",
                "reasoning_summary": "A motionless person on the ground may need urgent assistance.",
                "next_check": "Check whether the person responds and whether the area is safe to approach.",
                "risk_level": "High",
                "safest_next_action": "If the area is safe, approach, check responsiveness, and call emergency services.",
                "uncertainty": "Cause of the fall and the person's condition are unknown.",
                "detected_hazards": ["person_down"],
                "detected_objects": ["person", "floor", "corridor"],
                "people_detected": 1,
                "environment_conditions": ["normal visibility"],
                "motion_changes": "Stopped",
                "confidence": 0.85,
            },
            {
                "urgency": "Critical",
                "scene_summary": "The person remains unresponsive on the floor.",
                "situation": "Unresponsive person — likely medical emergency.",
                "voice_guidance": "Immediate help needed. Call emergency services now and stay with the person if safe.",
                "reasoning_summary": "Continued unresponsiveness indicates a serious medical emergency.",
                "next_check": "Confirm emergency services are contacted and monitor breathing.",
                "risk_level": "Critical",
                "safest_next_action": "Call emergency services, monitor breathing, and follow dispatcher guidance.",
                "uncertainty": "The person's breathing status is not confirmed from video.",
                "detected_hazards": ["person_down", "medical"],
                "detected_objects": ["person", "floor"],
                "people_detected": 1,
                "environment_conditions": ["normal visibility"],
                "motion_changes": "None",
                "confidence": 0.89,
            },
        ],
    },
    "gas_leak": {
        "label": "Gas leak warning",
        "icon": "alert",
        "frames": [
            {
                "urgency": "High",
                "scene_summary": "Indoor room, a sensor panel reads elevated gas levels.",
                "situation": "Possible gas leak in an enclosed space.",
                "voice_guidance": "Danger. Possible gas leak. Do not use switches or flames. Leave and ventilate the area.",
                "reasoning_summary": "Elevated gas in an enclosed space risks ignition and poisoning.",
                "next_check": "Confirm a path outdoors and avoid any electrical or spark sources.",
                "risk_level": "High",
                "safest_next_action": "Leave the area, avoid switches and flames, and get fresh air.",
                "uncertainty": "Gas type and concentration are not fully confirmed.",
                "detected_hazards": ["gas_leak"],
                "detected_objects": ["sensor panel", "appliance", "door"],
                "people_detected": 1,
                "environment_conditions": ["elevated gas reading", "enclosed space"],
                "motion_changes": "Minor",
                "confidence": 0.8,
            },
            {
                "urgency": "Critical",
                "scene_summary": "Gas reading climbing rapidly toward a dangerous threshold.",
                "situation": "Rapidly rising gas concentration — ignition risk.",
                "voice_guidance": "Immediate danger. Get out now. Do not switch anything on or off. Move to open air.",
                "reasoning_summary": "Fast-rising concentration sharply raises explosion and exposure risk.",
                "next_check": "Confirm everyone is outside and emergency services are alerted.",
                "risk_level": "Critical",
                "safest_next_action": "Evacuate immediately to open air and call emergency services from outside.",
                "uncertainty": "Exact leak location is unknown.",
                "detected_hazards": ["gas_leak"],
                "detected_objects": ["sensor panel", "door"],
                "people_detected": 1,
                "environment_conditions": ["high gas reading", "enclosed space"],
                "motion_changes": "Rapid",
                "confidence": 0.9,
            },
        ],
    },
}

DEFAULT_SCENARIO = "fire_smoke"


def scenario_list() -> list[dict[str, str]]:
    """Lightweight catalog for the UI scenario selector."""
    return [
        {"id": key, "label": value["label"], "icon": value["icon"]}
        for key, value in SCENARIOS.items()
    ]


def get_scenario(scenario_id: str) -> dict[str, Any]:
    return SCENARIOS.get(scenario_id, SCENARIOS[DEFAULT_SCENARIO])
